sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
before_cache:
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
branches:
  only:
  - master
install: true
script:
  - ./gradlew clean build --stacktrace
  - ./upload_to_bintray.sh
env:
  global:

